packages:
  - docs
  - packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - dtrace-provider
  - esbuild
  - sharp
  - simple-git-hooks
  - spawn-sync
autoInstallPeers: false
patchedDependencies:
  markdown-it-footnote: patches/markdown-it-footnote.patch
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - search-insights
    - svelte
